apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinenit-api-app
  labels:
    app: dinenit-api-app
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: dinenit-api-app
  template:
    metadata:
      labels:
        app: dinenit-api-app
    spec:
      containers:
        - name: dinenit-api-container
          image: dinenitacrdev.azurecr.io/dinenit-api-app:latest  # Change to your ACR image
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
