# 

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter  # <- Must match Service selector
    spec:
      hostPID: true
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
          args:
            - "--path.rootfs=/host"
          volumeMounts:
            - name: host
              mountPath: /host
              readOnly: true
      volumes:
        - name: host
          hostPath:
            path: /
