apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/prometheus/(api/.*)$ /$1 break;
      proxy_pass http://prometheus.monitoring.svc.cluster.local:9090;
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /prometheus/(api/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus
                port:
                  number: 9090