# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
#   labels:
#     app: prometheus
#   namespace: monitoring
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: 5s

#     scrape_configs:
#       - job_name: 'cadvisor'
#         static_configs:
#           - targets: ['cadvisor.monitoring.svc.cluster.local:8080']
#       # - job_name: 'kubernetes-pods'
#       #   kubernetes_sd_configs:
#       #     - role: pod
#       #   relabel_configs:
#       #     - source_labels: [__meta_kubernetes_pod_label_env]
#       #       regex: ".*"
#       #       action: keep
#       #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#       #       action: keep
#       #       regex: true
#       #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
#       #       action: replace
#       #       target_label: __metrics_path__
#       #       regex: (.+)
#       #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
#       #       action: replace
#       #       regex: (.+):(?:\d+);(\d+)
#       #       replacement: $1:$2
#       #       target_label: __address__

#       - job_name: 'kubernetes-pods'
#         kubernetes_sd_configs:
#           - role: pod
#         relabel_configs:
#           - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#             action: keep
#             regex: true
#           - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
#             action: replace
#             target_label: __metrics_path__
#             regex: (.+)
#           - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
#             action: replace
#             regex: (.+):(?:\d+);(\d+)
#             replacement: $1:$2
#             target_label: __address__
#           - source_labels: [__meta_kubernetes_namespace]
#             target_label: namespace
#           - source_labels: [__meta_kubernetes_pod_name]
#             target_label: pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.monitoring.svc.cluster.local:8080']

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-metrics.svc.cluster.local:8080']
